language: scala
jdk: openjdk8
scala:
- 2.12.9
- 2.11.12
script:
- sbt ++$TRAVIS_SCALA_VERSION test
before_install:
- openssl aes-256-cbc -K $encrypted_5a199264f440_key -iv $encrypted_5a199264f440_iv
  -in secret-key.asc.enc -out secret-key.asc -d
